version: "2"

services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
#    container_name: elasticsearch_container
#    environment:
#      - http.host=0.0.0.0
#      - transport.host=0.0.0.0
#      - xpack.security.enabled=false
#      - cluster.name=hive
#      - script.inline=true
#      - thread_pool.index.queue_size=100000
#      - thread_pool.search.queue_size=100000
#      - thread_pool.bulk.queue_size=100000
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    networks:
#      - cuckoo_net
#
#  cortex:
#    image: thehiveproject/cortex:latest
#    ports:
#      - "9001:9001"
#    networks:
#      - cuckoo_net
#
#  thehive:
#    image: thehiveproject/thehive:latest
#    depends_on:
#      - elasticsearch
#      - cortex
#    ports:
#      - "9000:9000"
#    networks:
#      - cuckoo_net

  build_image:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CUCKOO_UID=1000
    image: amf_cuckoo:0.2
    networks:
      - cuckoo_net

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo/:/data/db
    networks:
      cuckoo_net:
        ipv4_address: 172.21.0.5  # Fix the IP address to 172.21.0.5

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cuckoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data/pgdata
    networks:
      cuckoo_net:
        ipv4_address: 172.21.0.6  # Fix the IP address to 172.21.0.6

  cuckoo:
    container_name: cuckoo
    depends_on:
      - build_image
      - postgres
      - mongo
    image: amf_cuckoo:0.2
    command: daemon
    ports:
      - "2042:2042"
      - "18083:18083"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./volumes/tmp/:/tmp/cuckoo-tmp/
      - ./volumes/storage/:/cuckoo/storage/
      - ./conf/:/cuckoo/conf/
    env_file:
      - ./config-file.env
    environment:
      - POSTGRES_HOST=172.21.0.6
      - MONGO_HOST=172.21.0.5  # Use the fixed IP address 172.21.0.5 for Mongo
    restart: unless-stopped
    networks:
      - cuckoo_net

  web:
    container_name: cuckoo_web
    depends_on:
      - cuckoo
    image: amf_cuckoo:0.2
    ports:
      - "9091:31337"
    links:
      - mongo
      - postgres
    command: web
    volumes:
      - ./volumes/tmp/:/tmp/cuckoo-tmp/
      - ./volumes/storage/:/cuckoo/storage/
    env_file:
      - ./config-file.env
    environment:
      - POSTGRES_HOST=172.21.0.6
      - MONGO_HOST=172.21.0.5  # Use the fixed IP address 172.21.0.5 for Mongo
    restart: unless-stopped
    networks:
      - cuckoo_net

  api:
    container_name: cuckoo_api
    depends_on:
      - cuckoo
    image: amf_cuckoo:0.2
    ports:
      - "9092:1337"
    links:
      - postgres
    command: api
    volumes:
      - ./volumes/tmp/:/tmp/cuckoo-tmp/
      - ./volumes/storage/:/cuckoo/storage/
    env_file:
      - ./config-file.env
    environment:
      - POSTGRES_HOST=172.21.0.6
      - MONGO_HOST=172.21.0.5  # Use the fixed IP address 172.21.0.5 for Mongo
    restart: unless-stopped
    networks:
      - cuckoo_net

networks:
  cuckoo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  cuckoo-data:
  mongo-data:
  postgres-data:
